package com.auth.auth_service.enums;

public enum PermissionCode {
    // USER MANAGEMENT
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_VIEW,

    // ROLE & PERMISSION MANAGEMENT
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    ROLE_ASSIGN,

    PERMISSION_CREATE,
    PERMISSION_VIEW,

    // TASK MANAGEMENT
    TASK_CREATE,
    TASK_ASSIGN,
    TASK_UPDATE,
    TASK_DELETE,
    TASK_VIEW,
    TASK_STATUS_UPDATE
}
